var abilities = {
	portal: {
		type: "monster",
		name: "Portal",
		explanation: "Open a portal to different maps and instances",
		applicability: "monster",
	},
	self_healing: {
		type: "monster",
		name: "Healing",
		explanation: "Periodical self healing",
		applicability: "monster",
	},
	healing: {
		type: "monster",
		name: "Healing",
		explanation: "Heals an ally or self",
		applicability: "monster",
	},
	anger: {
		type: "monster",
		name: "Anger",
		explanation: "Randomly targets someone",
		hostile: true,
		applicability: "monster",
	},
	zap: {
		type: "monster",
		name: "Zap",
		explanation: "Zaps you with a pure damage ray",
		damage: 1200,
		hostile: true,
		projectile: "sburst",
		damage_type: "pure",
		applicability: "monster",
	},
	fireball: {
		type: "monster",
		name: "Fireball",
		explanation: "Hurls a fireball!",
		damage: 4000,
		hostile: true,
		projectile: "magic",
		damage_type: "magical",
		applicability: "monster",
	},
	frostball: {
		type: "monster",
		name: "Frostball",
		explanation: "Hurls a frostball!",
		damage: 800,
		hostile: true,
		projectile: "frostball",
		damage_type: "magical",
		applicability: "monster",
	},
	warpstomp: {
		type: "monster",
		name: "Warpstomp",
		explanation: "Warps to a random player nearby and stomps players in vicinity",
		hostile: true,
		applicability: "monster",
	},
	deepfreeze: {
		type: "monster",
		name: "Deepfreeze",
		explanation: "Randomly freezes a nearby opponent",
		damage: 1200,
		hostile: true,
		projectile: "burst",
		damage_type: "pure",
		applicability: "monster",
	},
	multi_burn: {
		type: "monster",
		name: "Multi Burn",
		explanation: "Hurl a fireball at everyone who dared attack him and burn them!",
		ui: true,
		hostile: true,
		skin: "essenceoffire",
		damage_type: "magical",
		applicability: "monster",
	},
	mlight: {
		type: "monster",
		name: "Light",
		explanation: "Reveals invisible entities nearby and prevents them from going invisible again for 12 seconds.",
		ui: true,
		hostile: true,
		skin: "skill_light",
		applicability: "monster",
	},
	dampening_aura: {
		type: "monster",
		name: "Dampening",
		explanation: "Prevents teleports",
		condition: "dampened",
		aura: true,
		hostile: true,
		passive: true,
		skin: "condition_neutral",
		duration: 300,
		applicability: "monster",
	},
	weakness_aura: {
		type: "monster",
		name: "Weakness",
		explanation: "Weakens",
		condition: "weakness",
		aura: true,
		hostile: true,
		passive: true,
		skin: "condition_bad",
		duration: 20000,
		applicability: "monster",
	},
	curse_aura: {
		type: "monster",
		name: "Curse",
		explanation: "A wretched aura",
		condition: "cursed",
		aura: true,
		hostile: true,
		passive: true,
		skin: "condition_bad",
		duration: 5000,
		applicability: "monster",
	},
	multi_freeze: {
		type: "monster",
		name: "Multi Freeze",
		explanation: "Hurl a frostball at everyone who dared attack him and freeze them!",
		hostile: true,
		ui: true,
		skin: "essenceoffrost",
		damage_type: "magical",
		applicability: "monster",
	},
	mtangle: {
		type: "monster",
		name: "Tangle",
		explanation: "Communicates through spores to activate dormant plants underneath. Slows down opponents significantly.",
		mp: 360,
		range: 480,
		cooldown: 40000,
		duration: 5000,
		condition: "tangled",
		target: true,
		monsters: true,
		hostile: true,
		applicability: "monster",
	},
	stone: {
		type: "monster",
		name: "Stone",
		explanation: "Looking into his eye for too long turns you to stone!",
		condition: "stoned",
		hostile: true,
		duration: 4000,
		applicability: "monster",
	},
	snowball: {
		type: "skill",
		skin: "snowball",
		consume: "snowball",
		name: "Snowball",
		explanation: "Throw a snowball at someone!",
		condition: "frozen",
		damage: 1,
		mp: 120,
		cooldown: 180,
		range: 720,
		projectile: "snowball",
		target: true,
		merchant_use: true,
		damage_type: "pure",
		duration: 5000,
		applicability: "item",
	},
	scare: {
		type: "skill",
		skin: "skill_scare",
		slot: [["orb", "jacko"]],
		name: "Scare",
		explanation: "Activate your Jack-o Lantern to scare away monsters targeting you!",
		mp: 50,
		cooldown: 5000,
		applicability: "item",
	},
	power: {
		type: "skill",
		skin: "powerglove",
		slot: [["gloves", "powerglove"]],
		name: "Power",
		explanation: "Unleash the power",
		mp: 320,
		cooldown: 500,
		condition: "power",
		duration: 4000,
		applicability: "item",
	},
	xpower: {
		type: "skill",
		skin: "goldenpowerglove",
		slot: [["gloves", "goldenpowerglove"]],
		name: "Power",
		explanation: "Unleash the power",
		mp: 320,
		cooldown: 500,
		condition: "xpower",
		duration: 6000,
		applicability: "item",
	},
	warp: {
		type: "skill",
		skin: "warpvest",
		slot: [["chest", "warpvest"]],
		name: "Warp",
		explanation: "Warp space to jump into any location",
		mp: 40,
		cooldown: 200,
		applicability: "item",
	},
	temporalsurge: {
		type: "skill",
		skin: "orboftemporal",
		slot: [["orb", "orboftemporal"]],
		name: "Temporal Surge",
		explanation: "Hasten nearby spawns 15% by tapping into temporal forces!",
		mp: 1000,
		cooldown: 60000,
		applicability: "item",
	},
	zapperzap: {
		type: "skill",
		skin: "trigger",
		slot: [
			["ring1", "zapper"],
			["ring2", "zapper"],
		],
		name: "Zap",
		explanation: "Zap your target for 200 damage",
		damage: 200,
		damage_type: "magical",
		mp: 140,
		cooldown: 200,
		range: 420,
		projectile: "gburst",
		target: true,
		hostile: true,
		applicability: "item",
	},
	charm: {
		type: "skill",
		skin: "charmer",
		slot: [["orb", "charmer"]],
		name: "Charm",
		explanation: "Charm a monster [%]",
		condition: "charmed",
		mp: 40,
		cooldown: 60000,
		target: "monster",
		hostile: true,
		use_range: true,
		duration: 30000,
		applicability: "item",
	},
	tangle: {
		type: "skill",
		skin: "heartwood",
		slot: [
			["mainhand", "heartwood"],
			["offhand", "heartwood"],
		],
		name: "Tangle",
		explanation: "Unleash the contained powers of nature to hinder an opponent.",
		mp: 40,
		cooldown: 60000,
		target: true,
		hostile: true,
		use_range: true,
		range_multiplier: 2,
		applicability: "item",
	},
	rspeed: {
		type: "skill",
		skin: "buff_speed",
		condition: "rspeed",
		name: "Rogue Swiftness",
		explanation: "Buff a target to increase their speed.",
		mp: 320,
		range: 320,
		level: 40,
		cooldown: 100,
		target: "player",
		duration: 2700000,
		applicability: "skill",
		skill: "rogue",
	},
	reflection: {
		type: "skill",
		skin: "buff_reflection",
		condition: "reflection",
		name: "Reflective Shield",
		explanation: "Erects a magical shield around the target to grant them +20% Reflection for the duration.",
		mp: 540,
		range: 320,
		level: 60,
		cooldown: 30000,
		target: "player",
		duration: 5000,
		applicability: "skill",
		skill: "mage",
	},
	pickpocket: {
		type: "skill",
		skin: "skill_pickpocket",
		name: "Pickpocket",
		explanation: "Try to steal a single PVP marked item from the target!",
		range: 15,
		level: 16,
		mp: 10,
		reuse_cooldown: 120000,
		duration_min: 200,
		duration_max: 2000,
		target: "player",
		persistent: true,
		applicability: "skill",
		skill: "rogue",
	},
	fishing: {
		type: "skill",
		skin: "skill_fishing",
		wtype: ["rod"],
		name: "Fishing",
		explanation: "Swing your rod and catch some fish!",
		range: 15,
		level: 16,
		mp: 120,
		reuse_cooldown: 2880000,
		duration_min: 5000,
		duration_max: 15000,
		persistent: true,
		applicability: "skill",
		skill: "merchant",
	},
	mining: {
		type: "skill",
		skin: "skill_mining",
		wtype: ["pickaxe"],
		name: "Mining",
		explanation: "Use your pickaxe to mine some mines!",
		range: 15,
		level: 16,
		mp: 120,
		reuse_cooldown: 7440000,
		duration_min: 5000,
		duration_max: 15000,
		persistent: true,
		applicability: "skill",
		skill: "merchant",
	},
	mluck: {
		type: "skill",
		skin: "buff_luck",
		condition: "mluck",
		name: "Merchant's Luck",
		explanation: "Buff a target to increase their luck. 2% chance for you to receive a duplicate of their looted items!",
		level: 40,
		mp: 10,
		range: 320,
		cooldown: 100,
		target: "player",
		duration: 3600000,
		applicability: "skill",
		skill: "merchant",
	},
	mcourage: {
		type: "skill",
		skin: "skill_mcourage",
		condition: "mcourage",
		name: "Merchant's Courage",
		explanation: "When you sense danger, you know what to do...",
		level: 70,
		mp: 2400,
		cooldown: 2000,
		duration: 10000,
		applicability: "skill",
		skill: "merchant",
	},
	mfrenzy: {
		type: "skill",
		skin: "skill_mfrenzy",
		condition: "mfrenzy",
		name: "Merchant's Frenzy",
		explanation: "When you sense danger, you know what to do!",
		level: 85,
		mp: 400,
		cooldown: 20000,
		duration: 5000,
		applicability: "skill",
		skill: "merchant",
	},
	massproduction: {
		type: "skill",
		skin: "skill_massproduction",
		condition: "massproduction",
		name: "Mass Production",
		explanation: "Adds a 1-time use buff that speeds up the next upgrade or compound by 50%. The buff expires in 10 seconds if not used.",
		level: 30,
		mp: 20,
		cooldown: 50,
		duration: 10000,
		applicability: "skill",
		skill: "merchant",
	},
	massproductionpp: {
		type: "skill",
		skin: "skill_massproductionpp",
		condition: "massproductionpp",
		name: "Mass Production++",
		explanation: "Adds a 1-time use buff that speeds up the next upgrade or compound by 90%. The buff expires in 10 seconds if not used.",
		level: 60,
		mp: 200,
		cooldown: 50,
		duration: 10000,
		applicability: "skill",
		skill: "merchant",
	},
	massexchange: {
		type: "skill",
		skin: "skill_massexchange",
		condition: "massexchange",
		name: "Mass Exchange",
		explanation: "Adds a 1-time use buff that speeds up the next exchange by 50%. The buff expires in 10 seconds if not used.",
		level: 40,
		mp: 30,
		cooldown: 50,
		duration: 10000,
		applicability: "skill",
		skill: "merchant",
	},
	massexchangepp: {
		type: "skill",
		skin: "skill_massexchangepp",
		condition: "massexchangepp",
		name: "Mass Exchange++",
		explanation: "Adds a 1-time use buff that speeds up the next exchange by 90%. The buff expires in 10 seconds if not used.",
		level: 70,
		mp: 200,
		cooldown: 50,
		duration: 10000,
		applicability: "skill",
		skill: "merchant",
	},
	throw: {
		type: "skill",
		skin: "skill_throw",
		name: "Throw Stuff",
		explanation: "Terrified? Just throw whatever you can find at your opponent!",
		range: 200,
		code: "range=character.skills.merchant.level+200",
		positive: ["essenceoflife"],
		negative: ["essenceoffire"],
		nprop: ["attack", "armor"],
		damage_type: "physical",
		level: 60,
		mp: 200,
		cooldown: 400,
		hostile: true,
		target: true,
		pierces_immunity: true,
		applicability: "skill",
		skill: "merchant",
	},
	burst: {
		type: "skill",
		skin: "skill_burst",
		name: "Mana Burst",
		explanation: "Converts your entire mana pool to pure damage. Deals 0.555 pure damage for each MP.",
		mp: 0,
		ratio: 0.555,
		cooldown: 6000,
		target: true,
		damage_type: "pure",
		hostile: true,
		projectile: "burst",
		use_range: true,
		applicability: "skill",
		skill: "mage",
		level: 1,
	},
	cburst: {
		type: "skill",
		skin: "skill_cburst",
		name: "Controlled Mana Burst",
		level: 75,
		explanation: "A skill for experienced mages. Allows you to control and channel your most powerful ability.",
		mp: 80,
		ratio: 0.5,
		cooldown: 240,
		list: true,
		hostile: true,
		projectile: "burst",
		use_range: true,
		damage_type: "magical",
		applicability: "skill",
		skill: "mage",
	},
	energize: {
		type: "skill",
		skin: "skill_energize",
		name: "Energize",
		range: 320,
		level: 20,
		explanation: "Transfers mana to a target. As a side effect the target gains high attack speed for a short duration.",
		cooldown: 4000,
		condition: "energized",
		target: "player",
		duration: 800,
		applicability: "skill",
		skill: "mage",
	},
	light: {
		type: "skill",
		skin: "skill_light",
		name: "Light",
		explanation: "Reveals invisible entities nearby and prevents them from going invisible again for 12 seconds.",
		mp: 2000,
		cooldown: 0,
		hostile: true,
		applicability: "skill",
		skill: "mage",
		level: 1,
	},
	blink: {
		type: "skill",
		skin: "skill_blink",
		name: "Blink",
		explanation: "Teleport to a nearby location.",
		mp: 1600,
		cooldown: 1200,
		applicability: "skill",
		skill: "mage",
		level: 1,
	},
	magiport: {
		type: "skill",
		skin: "skill_teleport",
		name: "Magiport",
		explanation: "Pull someone to your location using the magical paths that surround our world.",
		complementary: "Unless the target doesn't have a T2+ helmet, high MP, or a low level, it can't resist being magiported. (Reverted [03/07/18])",
		mp: 900,
		cooldown: 0,
		target: "player",
		global: true,
		applicability: "skill",
		skill: "mage",
		level: 1,
	},
	charge: {
		type: "skill",
		skin: "skill_charge",
		name: "Charge",
		explanation: "Gain 30 Speed for a short duration.",
		mp: 0,
		condition: "charging",
		cooldown: 40000,
		duration: 3200,
		applicability: "skill",
		skill: "warrior",
		level: 1,
	},
	dash: {
		type: "skill",
		skin: "skill_dash",
		name: "Dash",
		explanation: "Push forward, jumping over obstacles, climbing hills, defying physics!",
		mp: 120,
		set_speed: 500,
		cooldown: 0,
		applicability: "skill",
		skill: "warrior",
		level: 1,
	},
	taunt: {
		type: "skill",
		skin: "skill_taunt",
		name: "Taunt",
		explanation: "Taunts an enemy. Steals aggro from friendly targets.",
		range: 200,
		mp: 40,
		cooldown: 3000,
		damage: 1,
		target: true,
		hostile: true,
		projectile: "stone",
		pierces_immunity: true,
		applicability: "skill",
		skill: "warrior",
		level: 1,
	},
	agitate: {
		type: "skill",
		skin: "skill_agitate",
		name: "Agitate",
		explanation: "Taunts all nearby monsters.",
		range: 320,
		level: 68,
		mp: 420,
		cooldown: 2200,
		hostile: true,
		applicability: "skill",
		skill: "warrior",
	},
	hardshell: {
		type: "skill",
		skin: "skill_hardshell",
		name: "Hard Shell",
		explanation: "Use everything at your disposal to protect yourself from physical attacks for a short duration.",
		condition: "hardshell",
		level: 60,
		mp: 480,
		cooldown: 16000,
		duration: 8000,
		applicability: "skill",
		skill: "warrior",
	},
	cleave: {
		type: "skill",
		skin: "skill_cleave",
		wtype: ["axe", "scythe"],
		name: "Cleave",
		explanation: "Swing your axe in a flurry to damage all enemies nearby!",
		range: 160,
		level: 52,
		mp: 720,
		cooldown: 1200,
		hostile: true,
		pierces_immunity: true,
		damage_type: "physical",
		procs: true,
		applicability: "skill",
		skill: "warrior",
	},
	stomp: {
		type: "skill",
		skin: "skill_stomp",
		wtype: "basher",
		name: "Stomp",
		explanation: "Use your basher to Stomp the ground to Stun enemies nearby!",
		condition: "stunned",
		range: 400,
		level: 52,
		mp: 120,
		cooldown: 24000,
		duration: 3200,
		hostile: true,
		damage_type: "physical",
		applicability: "skill",
		skill: "warrior",
	},
	warcry: {
		type: "skill",
		skin: "skill_warcry",
		name: "War Cry",
		explanation: "Motivate your allies to fight!",
		level: 70,
		mp: 320,
		range: 600,
		cooldown: 60000,
		condition: "warcry",
		duration: 8000,
		applicability: "skill",
		skill: "warrior",
	},
	poisonarrow: {
		type: "skill",
		skin: "skill_poisonarrow",
		name: "Poison Arrow",
		explanation: "Fire a single low damage but poison coated arrow at your opponent.",
		wtype: ["bow", "crossbow"],
		cooldown: 300,
		damage: 200,
		mp: 360,
		consume: "poison",
		target: true,
		hostile: true,
		use_range: true,
		projectile: "poisonarrow",
		damage_type: "physical",
		condition: "poisoned",
		procs: true,
		duration: 5000,
		applicability: "skill",
		skill: "ranger",
		level: 1,
	},
	piercingshot: {
		type: "skill",
		skin: "skill_piercingshot",
		name: "Piercing Shot",
		explanation: "Fire heavy, armor piercing arrows at your opponent. They deal 75% of the damage but pierce through 500 armor.",
		wtype: ["bow", "crossbow"],
		apiercing: 500,
		damage_multiplier: 0.75,
		mp: 64,
		level: 72,
		cooldown_multiplier: 1,
		share: "attack",
		use_range: true,
		target: true,
		hostile: true,
		damage_type: "physical",
		procs: true,
		pierces_immunity: true,
		applicability: "skill",
		skill: "ranger",
	},
	huntersmark: {
		type: "skill",
		skin: "skill_huntersmark",
		name: "Hunter's Mark",
		explanation: "Mark an opponent for death, prevent them from stealthing away and increase damage done by 10%",
		mp: 240,
		condition: "marked",
		cooldown: 10000,
		target: true,
		hostile: true,
		range_multiplier: 3,
		range_bonus: 20,
		use_range: true,
		duration: 10000,
		applicability: "skill",
		skill: "ranger",
		level: 1,
	},
	pcoat: {
		type: "skill",
		skin: "skill_pcoat",
		name: "A Poisonous Touch",
		explanation: "Coat your blade with a poison sack. Poison everyone you damage before the venom dissipates.",
		condition: "poisonous",
		cooldown: 50000,
		duration: 7000,
		mp: 600,
		consume: "poison",
		applicability: "skill",
		skill: "rogue",
		level: 1,
	},
	invis: {
		type: "skill",
		skin: "skill_invis",
		name: "Assassin's Smoke",
		explanation: "Disappear into the shadows. Deal 1.25X damage when you sneak up on an enemy. Cooldown starts when you re-appear.",
		reuse_cooldown: 12000,
		applicability: "skill",
		skill: "rogue",
		level: 1,
	},
	mentalburst: {
		type: "skill",
		skin: "skill_mentalburst",
		name: "Mental Burst",
		explanation: "Channel your mental abilities for a magical blow. If the target is defeated, the damage dealt is converted to mana.",
		damage_type: "magical",
		cooldown: 900,
		damage_multiplier: 0.6,
		range_multiplier: 1.2,
		range_bonus: 32,
		mp: 180,
		target: true,
		requirements: {
			max_mp: 1060,
		},
		warning: "Highly unbalanced skill, could get nerfed or modified",
		hostile: true,
		projectile: "mentalburst",
		use_range: true,
		applicability: "skill",
		skill: "rogue",
		level: 1,
	},
	quickpunch: {
		type: "skill",
		skin: "skill_quickpunch",
		name: "Quick Punch",
		explanation: "Use your agility to quickly punch your opponent between your devastating attacks!",
		wtype: "fist",
		cooldown: 250,
		damage_multiplier: 0.25,
		mp: 240,
		use_range: true,
		target: true,
		hostile: true,
		projectile: "quickpunch",
		damage_type: "physical",
		pierces_immunity: true,
		applicability: "skill",
		skill: "rogue",
		level: 1,
	},
	quickstab: {
		type: "skill",
		skin: "skill_quickstab",
		name: "Quick Stab",
		explanation: "Use your agility to quickly stab your opponent between your devastating attacks!",
		wtype: "dagger",
		cooldown: 250,
		share: "quickpunch",
		damage_multiplier: 0.36,
		mp: 320,
		use_range: true,
		target: true,
		hostile: true,
		projectile: "quickstab",
		damage_type: "physical",
		procs: true,
		pierces_immunity: true,
		applicability: "skill",
		skill: "rogue",
		level: 1,
	},
	stack: {
		type: "passive",
		skin: "skill_stack",
		name: "Stacked Damage",
		explanation: "Slowly learning the ways of your opponent each rogue attack deals one more damage.",
		max: 2000,
		applicability: "skill",
		skill: "rogue",
		level: 1,
	},
	shadowstrike: {
		type: "skill",
		skin: "skill_shadowstrike",
		name: "Shadow Strike",
		explanation: "Use a shadow stone to strike a random enemy in a parallel universe!",
		range: 360,
		level: 70,
		mp: 320,
		cooldown: 1200,
		consume: "shadowstone",
		hostile: true,
		damage_type: "physical",
		applicability: "skill",
		skill: "rogue",
	},
	entangle: {
		type: "skill",
		skin: "skill_entangle",
		name: "Entangle",
		explanation: "Unleash the contained powers of nature to hinder an opponent.",
		level: 72,
		mp: 360,
		range: 480,
		cooldown: 40000,
		duration: 5000,
		condition: "tangled",
		target: true,
		monsters: true,
		consume: "essenceofnature",
		hostile: true,
		applicability: "skill",
		skill: "mage",
	},
	track: {
		type: "skill",
		skin: "skill_track",
		name: "Track",
		explanation: "Use your fine-tuned senses to detect others.",
		cooldown: 1600,
		range: 1440,
		mp: 80,
		applicability: "skill",
		skill: "ranger",
		level: 1,
	},
	supershot: {
		type: "skill",
		skin: "skill_supershot",
		name: "Supershot",
		explanation: "Deals 1.5X instant damage from an incredible distance.",
		wtype: ["bow", "crossbow"],
		damage_multiplier: 1.5,
		cooldown: 30000,
		range_multiplier: 3,
		range_bonus: 20,
		mp: 400,
		target: true,
		hostile: true,
		pierces_immunity: true,
		damage_type: "physical",
		procs: true,
		use_range: true,
		applicability: "skill",
		skill: "ranger",
		level: 1,
	},
	"3shot": {
		type: "skill",
		skin: "skill_3shot",
		name: "3-Shot",
		explanation: "Hits 3 targets at once! Deals 0.7X damage to each target.",
		wtype: ["bow", "crossbow"],
		damage_multiplier: 0.7,
		level: 60,
		mp: 200,
		cooldown_multiplier: 1,
		multi: true,
		share: "attack",
		hostile: true,
		pierces_immunity: true,
		damage_type: "physical",
		procs: true,
		use_range: true,
		applicability: "skill",
		skill: "ranger",
	},
	"5shot": {
		type: "skill",
		skin: "skill_5shot",
		name: "5-Shot",
		explanation: "Hits 5 targets at once! Deals 0.5X damage to each target.",
		wtype: ["bow", "crossbow"],
		damage_multiplier: 0.5,
		level: 75,
		mp: 320,
		cooldown_multiplier: 1,
		multi: true,
		share: "attack",
		hostile: true,
		pierces_immunity: true,
		damage_type: "physical",
		procs: true,
		use_range: true,
		applicability: "skill",
		skill: "ranger",
	},
	"4fingers": {
		type: "skill",
		skin: "skill_4fingers",
		name: "4 Finger Technique",
		explanation: "Use the ancient arts to send the target to a deep meditation state. Just several taps to key chakra points does the job!",
		level: 64,
		mp: 260,
		range: 120,
		cooldown: 40000,
		duration: 5000,
		condition: "fingered",
		target: "player",
		monsters: false,
		hostile: true,
		applicability: "skill",
		skill: "ranger",
	},
	curse: {
		type: "skill",
		skin: "skill_curse",
		name: "Curse",
		explanation: "Cursed opponents receive 20% more damage, deal 20% less damage and they slow down by 20.",
		mp: 400,
		range: 200,
		duration: 5000,
		cooldown: 5000,
		condition: "cursed",
		target: true,
		hostile: true,
		projectile: "curse",
		damage_type: "magical",
		applicability: "skill",
		skill: "priest",
		level: 1,
	},
	phaseout: {
		type: "skill",
		skin: "skill_phaseout",
		name: "Phase Out",
		explanation: "Absorb a shadow stone to phase yourself out from this universe.",
		level: 64,
		duration: 5000,
		cooldown: 4000,
		mp: 200,
		consume: "shadowstone",
		condition: "phasedout",
		applicability: "skill",
		skill: "priest",
	},
	darkblessing: {
		type: "skill",
		skin: "skill_dbuff",
		name: "Dark Blessing",
		explanation: "Increases damage by 25% for the duration.",
		level: 70,
		mp: 900,
		range: 600,
		duration: 8000,
		cooldown: 60000,
		condition: "darkblessing",
		applicability: "skill",
		skill: "priest",
	},
	absorb: {
		type: "skill",
		skin: "skill_absorbsins",
		name: "Absorb Sins",
		explanation: "Pulls all targets from a friendly character.",
		range: 240,
		cooldown: 400,
		mp: 200,
		level: 55,
		target: "player",
		applicability: "skill",
		skill: "priest",
	},
	partyheal: {
		type: "skill",
		skin: "skill_pheal",
		name: "Party Heal",
		explanation: "Heals all the party members.",
		output: 400,
		action: "heal",
		levels: [
			[0, 400],
			[60, 600],
			[72, 720],
			[80, 800],
		],
		mp: 400,
		cooldown: 200,
		party: true,
		projectile: "partyheal",
		damage_type: "magical",
		heal: true,
		multi: true,
		applicability: "skill",
		skill: "priest",
		level: 1,
	},
	selfheal: {
		type: "skill",
		skin: "skill_selfheal",
		name: "Heal",
		explanation: "Heal yourself",
		output: 400,
		action: "heal",
		levels: [
			[0, 400],
			[60, 600],
			[72, 720],
			[80, 800],
		],
		mp: 20,
		cooldown: 1200,
		projectile: "partyheal",
		damage_type: "magical",
		heal: true,
		applicability: "skill",
		skill: "paladin",
		level: 1,
	},
	mshield: {
		type: "skill",
		skin: "skill_mshield",
		name: "Mana Shield",
		explanation: "Create a magical shield around yourself to absorb damage [Toggle]",
		condition: "mshield",
		toggle: true,
		mp: 0,
		duration: 999999999,
		cooldown: 0,
		applicability: "skill",
		skill: "paladin",
		level: 1,
	},
	purify: {
		type: "skill",
		skin: "skill_purify",
		name: "Purify",
		level: 60,
		damage: 2000,
		damage_type: "pure",
		explanation: "Deals 2000 pure damage purifying the target, removes all buffs and debuffs dealing additional 400 damage for each and receive the Purifier buff if the target is defeated!",
		kill_buff: "purifier",
		projectile: "purify",
		hostile: true,
		target: true,
		mp: 360,
		cooldown: 24000,
		range: 480,
		applicability: "skill",
		skill: "paladin",
	},
	smash: {
		type: "skill",
		skin: "skill_smash",
		name: "Smash",
		explanation: "Smash your opponent using your mace!",
		wtype: "mace",
		cooldown: 320,
		level: 10,
		damage_multiplier: 0.36,
		mp: 380,
		use_range: true,
		target: true,
		hostile: true,
		projectile: "smash",
		damage_type: "physical",
		procs: true,
		pierces_immunity: true,
		applicability: "skill",
		skill: "paladin",
	},
	alchemy: {
		type: "skill",
		skin: "skill_alchemy",
		name: "Alchemy",
		explanation: "Dangerous skill, use with caution! Converts your firstfound item into pure gold!",
		variance: 0.2,
		output: 0.8,
		action: "rate",
		levels: [
			[40, 0.8],
			[50, 0.86],
			[60, 0.92],
			[70, 1],
			[80, 1.06],
			[90, 1.1],
			[100, 1.12],
		],
		level: 40,
		mp: 347,
		cooldown: 8000,
		party: true,
		applicability: "skill",
		skill: "mage",
	},
	revive: {
		type: "skill",
		skin: "skill_revive",
		name: "Revive!",
		explanation: "If a fallen comrade's gravestone has been healed fully, revives them using an Essence of Life!",
		mp: 500,
		cooldown: 200,
		range: 240,
		consume: "essenceoflife",
		target: "player",
		applicability: "skill",
		skill: "priest",
		level: 1,
	},
	regen_hp: {
		type: "ability",
		skin: "regen_hp",
		name: "Regenerate HP",
		share: "use_hp",
		cooldown_multiplier: 2,
		explanation: "Regenerate 50 HP without using potions.",
		applicability: "system",
	},
	regen_mp: {
		type: "ability",
		skin: "regen_mp",
		name: "Regenerate MP",
		share: "use_mp",
		cooldown_multiplier: 2,
		explanation: "Regenerate 100 MP without using potions.",
		applicability: "system",
	},
	use_mp: {
		type: "ability",
		skin: "use_mp",
		name: "Use MP Potion",
		explanation:
			"Uses an MP potion from your inventory. If there are multiple potions, the last one is used. If there are no potions, your character regenerates a small amount of MP with a high cooldown.",
		cooldown: 2000,
		applicability: "system",
	},
	use_hp: {
		type: "ability",
		skin: "use_hp",
		name: "Use HP Potion",
		explanation:
			"Uses an HP potion from your inventory. If there are multiple potions, the last one is used. If there are no potions, your character regenerates a small amount of HP with a high cooldown.",
		cooldown: 2000,
		applicability: "system",
	},
	use_town: {
		type: "ability",
		skin: "use_town",
		name: "Town",
		explanation: "Teleports you to the center of the map.",
		cooldown: 0,
		applicability: "system",
	},
	attack: {
		type: "ability",
		skin: "attack",
		name: "Attack",
		explanation: "Attack the target",
		target: true,
		hostile: true,
		pierces_immunity: true,
		use_range: true,
		projectile: "momentum",
		procs: true,
		applicability: "active_combat",
	},
	heal: {
		type: "ability",
		skin: "heal",
		name: "Heal",
		explanation: "Heal the target",
		cooldown_multiplier: 1,
		share: "attack",
		target: true,
		use_range: true,
		pierces_immunity: true,
		projectile: "plight",
		damage_type: "magical",
		heal: true,
		procs: true,
		applicability: "skill",
		skill: "priest",
		level: 1,
	},
	travel: {
		type: "ability",
		skin: "travel",
		name: "Travel!",
		explanation: "Where would you like to visit?",
		applicability: "system",
	},
	stop: {
		type: "ability",
		skin: "stop_g",
		name: "Stop",
		explanation: "Stops your character. Cancels all channeling abilities and active skills.",
		cooldown: 0,
		applicability: "system",
	},
	snippet: {
		type: "utility",
		skin: "run_snippet1",
		name: "Snippet",
		explanation: "Maps a code snippet to a keypress.",
		skins: ["run_snippet0", "run_snippet1", "run_snippet2"],
		code: true,
		applicability: "system",
	},
	emotion: {
		type: "utility",
		skin: "run_emotion",
		name: "Emotion",
		explanation: "Show a random emotion you've unlocked!",
		applicability: "system",
	},
	pure_eval: {
		type: "utility",
		skin: "run_eval0",
		name: "Pure Eval",
		explanation: "[Advanced] Maps a code snippet to be run directly inside the game, rather than using CODE. (Not to be confused with the text command, /eval, which evals inside the Code iframe)",
		skins: ["run_eval0", "run_eval1", "run_eval2"],
		code: true,
		applicability: "system",
	},
	esc: {
		type: "utility",
		skin: "esc",
		name: "ESC",
		explanation: "Calls the esc_pressed() function inside the game. Major functionality.",
		ui: false,
		applicability: "system",
	},
	move_up: {
		type: "utility",
		skin: "up",
		name: "Move Up",
		explanation: "Moves the character upwards",
		ui: false,
		applicability: "system",
	},
	move_down: {
		type: "utility",
		skin: "down",
		name: "Move Down",
		explanation: "Moves the character downwards",
		ui: false,
		applicability: "system",
	},
	move_left: {
		type: "utility",
		skin: "left",
		name: "Move Left",
		explanation: "Moves the character leftwards",
		ui: false,
		applicability: "system",
	},
	move_right: {
		type: "utility",
		skin: "right",
		name: "Move Right",
		explanation: "Moves the character rightwards",
		ui: false,
		applicability: "system",
	},
	toggle_code: {
		skin: "code",
		name: "Toggle Code",
		ui: false,
		applicability: "system",
	},
	toggle_run_code: {
		skin: "run_code",
		name: "Engage/Disengage Code",
		ui: false,
		applicability: "system",
	},
	toggle_inventory: {
		type: "utility",
		skin: "inventory",
		name: "Toggle Inventory",
		explanation: "Toggles the inventory",
		ui: false,
		applicability: "system",
	},
	toggle_stats: {
		type: "utility",
		skin: "stats",
		name: "Toggle Character Sheet",
		explanation: "Toggles the character sheet",
		ui: false,
		applicability: "system",
	},
	toggle_character: {
		type: "utility",
		skin: "character",
		name: "Toggle Character",
		explanation: "Toggles the character focus",
		ui: false,
		applicability: "system",
	},
	open_snippet: {
		type: "utility",
		skin: "snippet",
		name: "Open Snippet",
		explanation: "Open the Code Snippet interface",
		ui: false,
		applicability: "system",
	},
	interact: {
		type: "utility",
		skin: "interact",
		name: "Interact",
		explanation: "Interact with the nearest game entity, a door, doorway, or NPC.",
		ui: false,
		applicability: "system",
	},
	gm: {
		type: "gm",
		skin: "gm",
		name: "GM Abilities",
		explanation: "Jump, Jail, Mute, Use Any Skill",
		applicability: "system",
	},
};

var style_bound_abilities = [
	"rspeed",
	"reflection",
	"energize",
	"charge",
	"hardshell",
	"warcry",
	"pcoat",
	"invis",
	"phaseout",
	"darkblessing",
	"absorb",
	"mshield",
];
var support_weight_abilities = [
	"rspeed",
	"reflection",
	"energize",
	"taunt",
	"agitate",
	"stomp",
	"warcry",
	"huntersmark",
	"entangle",
	"curse",
	"darkblessing",
	"absorb",
];
style_bound_abilities.forEach(function (id) {
	if (abilities[id]) abilities[id].style_bound = true;
});
support_weight_abilities.forEach(function (id) {
	if (abilities[id]) {
		abilities[id].contribution = {
			weight_per_use: 1,
			max_weight_per_target_per_encounter: 10,
		};
	}
});

if (typeof module !== "undefined") module.exports = { abilities: abilities };
