var mining = {
	version: 1,
	respawn_ms: 10000,
	refresh_ms: 1000,
	map: "tunnel",
	success: {
		base: 0.45,
		level_step: 0.005,
		tool_step: 0.06,
		min: 0.05,
		max: 0.95,
	},
	cape: {
		item: "miningcape",
		level: 99,
		bonus: 0.05,
		price: 99000000,
	},
	balance: {
		double_speed_multiplier: 2,
		rotation_speed: 50,
		sell_multiplier: 0.6,
		rocks_per_tier: 3,
	},
	tiers: [
		{ index: 0, id: "copper", name: "Copper", level: 1, ore: "copperore", pickaxe: "pickaxe", xp: 800, duration_ms: 5000, ore_g: 20, pickaxe_g: 2000, art_column: 0 },
		{ index: 1, id: "iron", name: "Iron", level: 15, ore: "ironore", pickaxe: "ironpickaxe", xp: 1200, duration_ms: 4400, ore_g: 100, pickaxe_g: 100000, art_column: 1 },
		{ index: 2, id: "gold", name: "Gold", level: 30, ore: "goldore", pickaxe: "goldpickaxe", xp: 1800, duration_ms: 3800, ore_g: 500, pickaxe_g: 1000000, art_column: 2 },
		{ index: 3, id: "mithril", name: "Mithril", level: 55, ore: "mithrilore", pickaxe: "mithrilpickaxe", xp: 2800, duration_ms: 3200, ore_g: 2000, pickaxe_g: 8000000, art_column: 3 },
		{ index: 4, id: "adamantite", name: "Adamantite", level: 70, ore: "adamantiteore", pickaxe: "adamantitepickaxe", xp: 4000, duration_ms: 2600, ore_g: 8000, pickaxe_g: 35000000, art_column: 4 },
		{ index: 5, id: "runite", name: "Runite", level: 85, ore: "runiteore", pickaxe: "runitepickaxe", xp: 6000, duration_ms: 2000, ore_g: 32000, pickaxe_g: 150000000, art_column: 5 },
	],
	rocks: [
		{ id: "copper-1", map: "tunnel", tier: 0, x: -184, y: -136, range: 28, available_art: "mining_rock_copper", depleted_art: "mining_rock_copper_depleted" },
		{ id: "copper-2", map: "tunnel", tier: 0, x: 0, y: -168, range: 28, available_art: "mining_rock_copper", depleted_art: "mining_rock_copper_depleted" },
		{ id: "copper-3", map: "tunnel", tier: 0, x: 224, y: -192, range: 28, available_art: "mining_rock_copper", depleted_art: "mining_rock_copper_depleted" },
		{ id: "iron-1", map: "tunnel", tier: 1, x: -200, y: -328, range: 28, available_art: "mining_rock_iron", depleted_art: "mining_rock_iron_depleted" },
		{ id: "iron-2", map: "tunnel", tier: 1, x: 0, y: -376, range: 28, available_art: "mining_rock_iron", depleted_art: "mining_rock_iron_depleted" },
		{ id: "iron-3", map: "tunnel", tier: 1, x: 232, y: -432, range: 28, available_art: "mining_rock_iron", depleted_art: "mining_rock_iron_depleted" },
		{ id: "gold-1", map: "tunnel", tier: 2, x: -208, y: -544, range: 28, available_art: "mining_rock_gold", depleted_art: "mining_rock_gold_depleted" },
		{ id: "gold-2", map: "tunnel", tier: 2, x: 0, y: -608, range: 28, available_art: "mining_rock_gold", depleted_art: "mining_rock_gold_depleted" },
		{ id: "gold-3", map: "tunnel", tier: 2, x: 184, y: -656, range: 28, available_art: "mining_rock_gold", depleted_art: "mining_rock_gold_depleted" },
		{ id: "mithril-1", map: "tunnel", tier: 3, x: -96, y: -744, range: 28, available_art: "mining_rock_mithril", depleted_art: "mining_rock_mithril_depleted" },
		{ id: "mithril-2", map: "tunnel", tier: 3, x: 0, y: -808, range: 28, available_art: "mining_rock_mithril", depleted_art: "mining_rock_mithril_depleted" },
		{ id: "mithril-3", map: "tunnel", tier: 3, x: 112, y: -840, range: 28, available_art: "mining_rock_mithril", depleted_art: "mining_rock_mithril_depleted" },
		{ id: "adamantite-1", map: "tunnel", tier: 4, x: -208, y: -920, range: 28, available_art: "mining_rock_adamantite", depleted_art: "mining_rock_adamantite_depleted" },
		{ id: "adamantite-2", map: "tunnel", tier: 4, x: 0, y: -1016, range: 28, available_art: "mining_rock_adamantite", depleted_art: "mining_rock_adamantite_depleted" },
		{ id: "adamantite-3", map: "tunnel", tier: 4, x: 200, y: -1072, range: 28, available_art: "mining_rock_adamantite", depleted_art: "mining_rock_adamantite_depleted" },
		{ id: "runite-1", map: "tunnel", tier: 5, x: -232, y: -1168, range: 28, available_art: "mining_rock_runite", depleted_art: "mining_rock_runite_depleted" },
		{ id: "runite-2", map: "tunnel", tier: 5, x: 0, y: -1256, range: 28, available_art: "mining_rock_runite", depleted_art: "mining_rock_runite_depleted" },
		{ id: "runite-3", map: "tunnel", tier: 5, x: 192, y: -1304, range: 28, available_art: "mining_rock_runite", depleted_art: "mining_rock_runite_depleted" },
	],
	legacy_bonus: {
		old_attempt_ms: 7440000,
		old_success: 0.2,
		rewards: [
			[200, "gemfragment"],
			[1, "bronzenugget"],
			[0.5, "goldnugget"],
			[0.1, "platinumnugget"],
		],
	},
};

if (typeof module !== "undefined") module.exports = { mining: mining };
