var progression = {
	MAX_LEVEL: 99,
	MAX_XP: 900000000,
	STAND_HOUR_MS: 3600000,
	STAND_SETTLEMENT_MS: 300000,
	DEATH_SICKNESS_MS: 300000,
	DEATH_SICKNESS_MULTIPLIER: 0.8,
	BASE_UNITS_PER_HOUR: 3125000,
	XP_UNITS_PER_XP: 7,
	MAX_ACTION_UNITS_PER_HOUR: 15625000,
	MAX_TOTAL_UNITS_PER_HOUR: 18750000,
	LUCK_UNITS: 1250000,
	LUCK_MAX_TARGETS_PER_HOUR: 10,
	MAX_COLLECTION_SIZE: 1000,
	SKILL_XP_SOURCE_RETENTION_MS: 24 * 60 * 60 * 1000,
	MAX_SKILL_XP_SOURCES: 1000,
	MAX_LUCK_COLLECTION_SIZE: 10,
	SUPPORT_WEIGHT_PER_USE: 1,
	SUPPORT_MAX_WEIGHT_PER_TARGET_PER_ENCOUNTER: 10,
	BENCHMARK_TOLERANCE: 0.1,
	MERCHANT_ENHANCEMENT_XP: Object.freeze({
		upgrade: 200,
		compound: 600,
	}),
	XP_SOURCES: [
		"pve_damage",
		"pve_heal",
		"pve_support",
		"merchant_stand",
		"merchant_luck",
		"merchant_sale",
		"merchant_donation",
		"merchant_dice",
		"merchant_upgrade",
		"merchant_compound",
	],
};

if (typeof module !== "undefined") module.exports = { progression: progression };
